# Generated by Django 5.0.6 on 2024-06-04 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_request'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='username',
        ),
    ]
